version: 2
jobs:
  test:
    docker:
      - image: kirkstrobeck/integration

    # working_directory: ~/repo

    steps:
      - checkout

      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn install

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}

      - run: node index.js

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
