version: 2
jobs:
  test:
    docker:
      - image: kirkstrobeck/integration

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: node index.js

      - store_artifacts:
          path: tmp

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
