version: 2
jobs:
  test:
    docker:
      - image: circleci/node:11.6.0
    steps:
      - checkout
      - run: yarn && node index.js
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
